a=int(input("Enter a no1 : "))
b=int(input("Enter a no2 : "))
# c=int(a)+int(b)
print("Addition is : ",a+b)
print("Subtraction is : ",a-b)
print("Divison is : ",a/b)
print("Multiplication is : ",a*b)
print("Reminder : ",a%b)
print("power : ",a**b)
